TestApplication/Controllers/CustomerController.cs
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mtd.DbmsRandomizer.DatabaseManagement;
using TestApplication.Pages;

namespace TestApplication.Controllers
{
	[Route("/customer")]
	public class CustomerController : Controller
	{
		private readonly IDatabaseManager _databaseManager;

		public CustomerController(IDatabaseManager databaseManager)
		{
			_databaseManager = databaseManager;
		}

		[HttpPost]
		[ActionName("AddCustomer")]
		public async Task<IActionResult> AddCustomer(CustomerModel model)
		{
			await _databaseManager.Context.ExecuteNonQueryAsync($"insert into customers (name, surname, favorite_number) values ({{0}}, {{1}}, '{model.Favorite_Number}')", new CancellationToken(), model.Name, model.Surname);
			return View("success");
		}
	}
}

TestApplication/Controllers/FindCustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Mtd.DbmsRandomizer.DatabaseManagement;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using TestApplication.Pages;
using TestApplication.Pages.Shared;

namespace TestApplication.Controllers
{
	[Route("/findCustomer")]
	public class FindCustomerController : Controller
	{
		private readonly IDatabaseManager _databaseManager;

		public IActionResult Index()
		{
			return View();
		}

		public FindCustomerController(IDatabaseManager databaseManager)
		{
			_databaseManager = databaseManager;
		}
		[HttpPost]
		public ActionResult FindCustomer(string surname)
		{
			var result = _databaseManager.Context.ExecuteQueryAsync<CustomerModel>($"select * from dbo.customers where surname = {{0}}", new CancellationToken(), surname);
			var r = result.ToListAsync();
			var model = new FindCustomerModel()
			{
				List = r.Result
			};
			return View(model);
		}

	}
}

TestApplication/Pages/AddCustomer.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestApplication.Pages
{
	public class AddCustomerModel
	{
		[Required]
		[BindProperty]
		public string Name { get; set; }
		[Required]
		[BindProperty]
		public string Surname { get; set; }
		[Required]
		[BindProperty]
		public string FavoriteNumber { get; set; }

	}
}

TestApplication/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace TestApplication.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public class ErrorModel : PageModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

TestApplication/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestApplication.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;

		public IndexModel(ILogger<IndexModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{

		}
	}
}

TestApplication/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestApplication.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

TestApplication/Pages/Shared/AddCustomer.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestApplication.Pages
{
	public class CustomerModel
	{
		[Required]
		[BindProperty]
		public string Name { get; set; }
		[Required]
		[BindProperty]
		public string Surname { get; set; }
		[Required]
		[BindProperty]
		public string Favorite_Number { get; set; }

	}
}

TestApplication/Pages/Shared/FindCustomer.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestApplication.Pages.Shared
{
	public class FindCustomerModel : PageModel
    {
        [BindProperty]
        public string X { get; set; } = "abc";

        public List<CustomerModel> List { get; set; } = new List<CustomerModel>();

    }
}

TestApplication/Pages/Shared/success.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestApplication.Pages.Shared
{
    public class successModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TestApplication/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <a href="shared/addcustomer">abc</a>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TestApplication/Pages/Shared/AddCustomer.cshtml
@page 
@model TestApplication.Pages.CustomerModel
<span>Add user</span>
<form method="post" asp-controller="Customer" asp-action="AddCustomer">
    <input asp-for="Name"/>
    <input asp-for="Surname"/>
    <input asp-for="Favorite_Number"/>
    <input type="submit"/>
</form>
<span>Find user</span>
<form method="post" asp-controller="FindCustomer" asp-action="FindCustomer">
    <input asp-for="Surname" />
    <input type="submit" />
</form>

TestApplication/Pages/Shared/FindCustomer.cshtml
@model TestApplication.Pages.Shared.FindCustomerModel
@{
    <table class="table table-bordered table-responsive table-hover">
        <tr>
            <th>Name</th>
            <th>Surname</th>
            <th>FavoriteNumber </th>
        </tr>
        @foreach (var d in Model.List)
        {
            <tr>
                <td>@d.Name</td>
                <td>@d.Surname</td>
                <td>@d.Favorite_Number</td>
            </tr>

        }
    </table>
}

TestApplication/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">TestApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TestApplication - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

TestApplication/Pages/Shared/success.cshtml
@page
@model TestApplication.Pages.Shared.successModel
@{
    <span>Sucess!</span>
}